name: Pull Request CI

on:
  pull_request: ~

jobs:
  prcheck:
    runs-on: ubuntu-latest

    steps:
# Checkout source code
    - uses: actions/checkout@v2

    - name: Build and test
      run: ./build/build.sh
